name: Publish to PyPI

on:
  push:
    tags:
      - "v*"          # e.g. v0.0.0a0
    branches:
      - main          # remove this line if you only want tag releases
  workflow_dispatch:   # manual button in the Actions UI

permissions:
  id-token: write       # required for PyPI‑OIDC
  contents: read

jobs:
  build-and-publish:
    name: Build & upload to PyPI
    runs-on: ubuntu-latest
    environment: pypi        # must exist in repo Settings → Environments

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Build sdist & wheel
        run: |
          poetry build

      - name: Publish to PyPI via Trusted Publisher
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          print-hash: true        # optional, shows SHA256 of artifacts
